# Generated by Django 3.1.7 on 2021-03-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_the_exam', models.IntegerField()),
                ('exam_description', models.TextField()),
                ('dead_line', models.DateField()),
            ],
        ),
    ]
