# Generated by Django 3.1.7 on 2021-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0002_auto_20210302_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_video', models.TextField()),
            ],
        ),
    ]
