# Generated by Django 3.1.7 on 2021-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='vid',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
