# Generated by Django 3.1.7 on 2021-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0007_auto_20210304_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_video', models.TextField(max_length=30)),
                ('vid', models.FileField(null=True, upload_to='mainone/media')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
