# Generated by Django 3.1.7 on 2021-03-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0010_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentexercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.FileField(null=True, upload_to='media')),
                ('score', models.IntegerField(null=True, verbose_name=range(0, 100))),
                ('numberassignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainone.assignment')),
            ],
        ),
    ]
