# Generated by Django 3.1.7 on 2021-03-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0011_studentexercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercises',
            name='exercise',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='studentexercises',
            name='score',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name=range(0, 100)),
        ),
    ]
