# Generated by Django 3.1.7 on 2021-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0014_remove_studentexercises_numberassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercises',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
