# Generated by Django 3.1.7 on 2021-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0016_studentexercises_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercises',
            name='studentname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
