# Generated by Django 3.1.7 on 2021-03-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainone', '0017_studentexercises_studentname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexercises',
            name='exercise',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
